# Generated by Django 5.0.7 on 2024-09-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together={('plan', 'content_id')},
        ),
    ]
