# Generated by Django 5.0.7 on 2024-10-07 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_place_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('username', 'content_id')},
        ),
    ]
